//! Verify that bech32 invite strings generated by ec-gate round-trip correctly.

use ec_data::{HostedSeat, HostedSeatStatus};
use ec_gate::serve::catalog::HostedGame;
use ec_gate::serve::game_def::build_game_def_tags;
use ec_nostr::invite::decode_invite;
use nostr_sdk::Keys;

fn pending_seat(idx: usize, code: &str) -> HostedSeat {
    HostedSeat {
        player_record_index_1_based: idx,
        invite_code: code.to_string(),
        status: HostedSeatStatus::Pending,
        player_npub: None,
    }
}

fn claimed_seat(idx: usize, code: &str, npub: &str) -> HostedSeat {
    HostedSeat {
        player_record_index_1_based: idx,
        invite_code: code.to_string(),
        status: HostedSeatStatus::Claimed,
        player_npub: Some(npub.to_string()),
    }
}

#[test]
fn pending_seats_get_invite_bech32_tags() {
    let game = HostedGame {
        game_id: "friday-night".to_string(),
        game_name: "Friday Night EC".to_string(),
        seats: vec![
            pending_seat(1, "velvet-mountain"),
            claimed_seat(2, "copper-sunrise", "npub1aaa"),
        ],
    };
    let keys = Keys::generate();
    let tags = build_game_def_tags(
        &game,
        "play.example.com",
        2222,
        "wss://play.example.com:7777",
        &keys.public_key(),
    )
    .unwrap();

    let tag_vecs: Vec<Vec<String>> = tags.iter().map(|t| t.clone().to_vec()).collect();
    let bech32_tags: Vec<_> = tag_vecs
        .iter()
        .filter(|t| t[0] == "invite-bech32")
        .collect();

    // Only pending seats get bech32 tags.
    assert_eq!(bech32_tags.len(), 1);
    assert_eq!(bech32_tags[0][1], "1"); // seat index
}

#[test]
fn invite_bech32_tag_round_trips() {
    let relay = "wss://play.example.com:7777";
    let game = HostedGame {
        game_id: "friday-night".to_string(),
        game_name: "Friday Night EC".to_string(),
        seats: vec![pending_seat(1, "velvet-mountain")],
    };
    let keys = Keys::generate();
    let tags = build_game_def_tags(&game, "play.example.com", 2222, relay, &keys.public_key())
        .unwrap();
    let tag_vecs: Vec<Vec<String>> = tags.iter().map(|t| t.clone().to_vec()).collect();
    let bech32_tag = tag_vecs
        .iter()
        .find(|t| t[0] == "invite-bech32")
        .expect("invite-bech32 tag should be present");

    let encoded = &bech32_tag[2];
    let decoded = decode_invite(encoded).expect("bech32 invite should decode");
    assert_eq!(decoded.relay_url, relay);
    assert_eq!(decoded.words, "velvet-mountain");
    assert_eq!(decoded.ssh_host, "play.example.com");
    assert_eq!(decoded.ssh_port, 2222);
    assert_eq!(decoded.game_id, Some("friday-night".to_string()));
    assert!(decoded.gate_npub.is_some());
}

#[test]
fn claimed_seats_have_no_invite_bech32_tag() {
    let game = HostedGame {
        game_id: "friday-night".to_string(),
        game_name: "Friday Night EC".to_string(),
        seats: vec![claimed_seat(1, "velvet-mountain", "npub1aaa")],
    };
    let keys = Keys::generate();
    let tags = build_game_def_tags(
        &game,
        "play.example.com",
        2222,
        "wss://play.example.com:7777",
        &keys.public_key(),
    )
    .unwrap();
    let tag_vecs: Vec<Vec<String>> = tags.iter().map(|t| t.clone().to_vec()).collect();
    assert!(tag_vecs.iter().all(|t| t[0] != "invite-bech32"));
}
