use crate::domains::startup::screens::startup::StartupReviewMode;
use crate::screen::ScreenId;
use crate::theme::ThemeEntry;
pub use nc_session::onboarding::FirstTimeOnboardingMode;

pub struct StartupState {
    pub startup_status: Option<String>,
    pub splash_page: usize,
    pub intro_page: usize,
    pub results_block: usize,
    pub results_page: usize,
    pub results_mode: StartupReviewMode,
    pub results_nonstop: bool,
    pub messages_block: usize,
    pub messages_page: usize,
    pub messages_mode: StartupReviewMode,
    pub messages_nonstop: bool,
    pub results_deleted_any: bool,
    pub messages_deleted_any: bool,
    pub results_review_history_rows: Vec<String>,
    pub messages_review_history_rows: Vec<String>,
    pub first_time_intro_page: usize,
    pub first_time_rename_preloaded_empire: bool,
    pub first_time_status: Option<String>,
    pub theme_picker_rows: Vec<ThemeEntry>,
    pub theme_picker_cursor: usize,
    pub theme_picker_scroll_offset: usize,
    pub theme_picker_input: String,
    pub theme_picker_status: Option<String>,
    pub theme_picker_return_screen: Option<ScreenId>,
    pub prejoin_theme_key: Option<String>,
    pub caller_alias: Option<String>,
    pub reserved_seat_alias: Option<String>,
    pub unbound_bbs_caller: bool,
    pub fixed_player_launch: bool,
    pub first_time_input: String,
    pub first_time_empire_name: String,
    pub first_time_homeworld_name: String,
    pub first_time_onboarding_mode: FirstTimeOnboardingMode,
    pub colony_world_name: String,
    pub colony_world_planet_record_index_1_based: Option<usize>,
}

impl Default for StartupState {
    fn default() -> Self {
        Self {
            startup_status: None,
            splash_page: 0,
            intro_page: 0,
            results_block: 0,
            results_page: 0,
            results_mode: StartupReviewMode::ViewPrompt,
            results_nonstop: false,
            messages_block: 0,
            messages_page: 0,
            messages_mode: StartupReviewMode::ViewPrompt,
            messages_nonstop: false,
            results_deleted_any: false,
            messages_deleted_any: false,
            results_review_history_rows: Vec::new(),
            messages_review_history_rows: Vec::new(),
            first_time_intro_page: 0,
            first_time_rename_preloaded_empire: false,
            first_time_status: None,
            theme_picker_rows: Vec::new(),
            theme_picker_cursor: 0,
            theme_picker_scroll_offset: 0,
            theme_picker_input: String::new(),
            theme_picker_status: None,
            theme_picker_return_screen: None,
            prejoin_theme_key: None,
            caller_alias: None,
            reserved_seat_alias: None,
            unbound_bbs_caller: false,
            fixed_player_launch: false,
            first_time_input: String::new(),
            first_time_empire_name: String::new(),
            first_time_homeworld_name: String::new(),
            first_time_onboarding_mode: FirstTimeOnboardingMode::Generic,
            colony_world_name: String::new(),
            colony_world_planet_record_index_1_based: None,
        }
    }
}
