use ec_data::EmpireProductionRankingSort;
use crate::screen::{CommandMenu, PlanetListMode, PlanetListSort};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    AdvanceStartup,
    OpenStartupIntro,
    OpenMainMenu,
    OpenGeneralMenu,
    OpenGeneralHelp,
    OpenPlanetMenu,
    OpenPlanetHelp,
    OpenPlanetListSortPrompt(PlanetListMode),
    SubmitPlanetListSort(PlanetListMode, PlanetListSort),
    ReturnToCommandMenu,
    OpenStarmap,
    OpenPartialStarmapPrompt(CommandMenu),
    OpenEnemies,
    OpenDeleteReviewables,
    OpenComposeMessageRecipient,
    OpenComposeMessageSubject,
    OpenComposeMessageBody,
    OpenComposeMessageOutbox,
    OpenComposeMessageDiscardConfirm,
    OpenComposeMessageSendConfirm,
    BeginStarmapDump,
    AdvanceStarmapPage,
    ExportStarmap,
    ToggleAutopilot,
    ScrollEnemies(i8),
    ScrollPlanetBrief(i8),
    MovePlanetDetail(i8),
    ScrollComposeRecipients(i8),
    ScrollComposeOutbox(i8),
    AppendPartialStarmapChar(char),
    BackspacePartialStarmapInput,
    SubmitPartialStarmapPrompt,
    MovePartialStarmap(i8, i8),
    AppendEnemiesChar(char),
    BackspaceEnemiesInput,
    SubmitEnemiesInput,
    ConfirmDeleteReviewables,
    AppendComposeRecipientChar(char),
    BackspaceComposeRecipient,
    SubmitComposeRecipient,
    AppendComposeSubjectChar(char),
    BackspaceComposeSubject,
    SubmitComposeSubject,
    AppendComposeBodyChar(char),
    BackspaceComposeBody,
    DeleteComposeBodyChar,
    InsertComposeNewline,
    MoveComposeBodyCursorLeft,
    MoveComposeBodyCursorRight,
    MoveComposeBodyCursorUp,
    MoveComposeBodyCursorDown,
    MoveComposeBodyCursorHome,
    MoveComposeBodyCursorEnd,
    SendComposedMessage,
    AppendComposeOutboxChar(char),
    BackspaceComposeOutboxInput,
    DeleteQueuedComposeMessage,
    ConfirmDiscardComposedMessage,
    ConfirmSendComposedMessage,
    OpenPlanetInfoPrompt(CommandMenu),
    AppendPlanetInfoChar(char),
    BackspacePlanetInfoInput,
    SubmitPlanetInfoPrompt,
    OpenEmpireStatus,
    OpenEmpireProfile,
    OpenRankingsPrompt,
    OpenRankingsTable(EmpireProductionRankingSort),
    OpenReports,
    Quit,
    Noop,
}
