use ec_data::EmpireProductionRankingSort;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    AdvanceStartup,
    OpenStartupIntro,
    OpenMainMenu,
    OpenGeneralMenu,
    OpenStarmap,
    OpenPartialStarmapPrompt,
    OpenEnemies,
    OpenDeleteReviewables,
    OpenComposeMessageRecipient,
    BeginStarmapDump,
    AdvanceStarmapPage,
    ExportStarmap,
    ToggleAutopilot,
    ScrollEnemies(i8),
    ScrollComposeRecipients(i8),
    AppendPartialStarmapChar(char),
    BackspacePartialStarmapInput,
    SubmitPartialStarmapPrompt,
    MovePartialStarmap(i8, i8),
    AppendEnemiesChar(char),
    BackspaceEnemiesInput,
    SubmitEnemiesInput,
    ConfirmDeleteReviewables,
    AppendComposeRecipientChar(char),
    BackspaceComposeRecipient,
    SubmitComposeRecipient,
    AppendComposeBodyChar(char),
    BackspaceComposeBody,
    InsertComposeNewline,
    SendComposedMessage,
    OpenPlanetInfoPrompt,
    AppendPlanetInfoChar(char),
    BackspacePlanetInfoInput,
    SubmitPlanetInfoPrompt,
    OpenEmpireStatus,
    OpenEmpireProfile,
    OpenRankingsPrompt,
    OpenRankingsTable(EmpireProductionRankingSort),
    OpenReports,
    Quit,
    Noop,
}
