//! Wallet types: in-memory representation of the decrypted wallet.

pub mod crypto;
pub mod io;

use nostr_sdk::{Keys, ToBech32};

pub use io::{load_wallet, save_wallet, wallet_path};

pub const MAX_IDENTITIES: usize = 10;

/// Type of a wallet identity entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IdentityType {
    /// Auto-generated by ec-connect on first launch.
    Local,
    /// Imported by the player from an existing nsec.
    Imported,
}

impl IdentityType {
    pub fn as_str(&self) -> &'static str {
        match self {
            IdentityType::Local => "local",
            IdentityType::Imported => "imported",
        }
    }

    pub fn parse(s: &str) -> Result<Self, String> {
        match s {
            "local" => Ok(IdentityType::Local),
            "imported" => Ok(IdentityType::Imported),
            other => Err(format!("unknown identity type: {other}")),
        }
    }
}

/// One identity entry in the wallet.
#[derive(Debug, Clone)]
pub struct Identity {
    /// Nostr secret key in nsec bech32 format.
    pub nsec: String,
    /// Whether this identity was generated locally or imported.
    pub identity_type: IdentityType,
    /// ISO-8601 creation timestamp (UTC, second precision).
    pub created: String,
    /// Optional local-only display label for this identity.
    pub alias: Option<String>,
}

/// The in-memory wallet: a list of identities with one active.
#[derive(Debug, Clone)]
pub struct Wallet {
    /// Index into `identities` of the currently active identity.
    /// Stored as a string in KDL; parsed as `usize`.
    pub active: usize,
    /// Ordered list of identity entries.
    pub identities: Vec<Identity>,
}

impl Wallet {
    /// Create an empty wallet (no identities, active = 0).
    pub fn empty() -> Self {
        Wallet {
            active: 0,
            identities: Vec::new(),
        }
    }

    /// Return the active identity, if one exists.
    pub fn active_identity(&self) -> Option<&Identity> {
        self.identities.get(self.active)
    }
}

pub fn identity_npub(identity: &Identity) -> Result<String, Box<dyn std::error::Error>> {
    let keys = Keys::parse(&identity.nsec)?;
    Ok(keys.public_key().to_bech32()?)
}

pub fn active_identity_npub(wallet: &Wallet) -> Result<String, Box<dyn std::error::Error>> {
    let identity = wallet
        .active_identity()
        .ok_or("wallet has no active identity")?;
    identity_npub(identity)
}

pub fn push_new_identity(
    wallet: &mut Wallet,
    created: String,
) -> Result<String, Box<dyn std::error::Error>> {
    if wallet.identities.len() >= MAX_IDENTITIES {
        return Err(format!("wallet already has {MAX_IDENTITIES} identities (maximum)").into());
    }

    let keys = Keys::generate();
    let npub = keys.public_key().to_bech32()?;
    wallet.identities.push(Identity {
        nsec: keys.secret_key().to_bech32()?,
        identity_type: IdentityType::Local,
        created,
        alias: None,
    });
    Ok(npub)
}

pub fn push_identity_from_input(
    wallet: &mut Wallet,
    input: &str,
    created: String,
) -> Result<String, Box<dyn std::error::Error>> {
    let trimmed = input.trim();
    if trimmed.is_empty() {
        push_new_identity(wallet, created)
    } else {
        push_imported_identity(wallet, trimmed, created)
    }
}

pub fn push_imported_identity(
    wallet: &mut Wallet,
    nsec_input: &str,
    created: String,
) -> Result<String, Box<dyn std::error::Error>> {
    if wallet.identities.len() >= MAX_IDENTITIES {
        return Err(format!("wallet already has {MAX_IDENTITIES} identities (maximum)").into());
    }

    let keys = Keys::parse(nsec_input).map_err(|e| format!("invalid nsec: {e}"))?;
    let nsec = keys.secret_key().to_bech32()?;
    let npub = keys.public_key().to_bech32()?;

    if wallet
        .identities
        .iter()
        .any(|identity| identity.nsec == nsec)
    {
        return Err("this identity is already in the wallet".into());
    }

    wallet.identities.push(Identity {
        nsec,
        identity_type: IdentityType::Imported,
        created,
        alias: None,
    });
    Ok(npub)
}

pub fn switch_active_identity(
    wallet: &mut Wallet,
    index: usize,
) -> Result<String, Box<dyn std::error::Error>> {
    if index >= wallet.identities.len() {
        return Err(format!(
            "index {index} out of range (wallet has {} identit{})",
            wallet.identities.len(),
            if wallet.identities.len() == 1 {
                "y"
            } else {
                "ies"
            },
        )
        .into());
    }

    wallet.active = index;
    active_identity_npub(wallet)
}

pub fn set_identity_alias(
    wallet: &mut Wallet,
    index: usize,
    alias: Option<String>,
) -> Result<(), Box<dyn std::error::Error>> {
    let identity = wallet
        .identities
        .get_mut(index)
        .ok_or_else(|| format!("index {index} out of range"))?;
    identity.alias = alias
        .map(|alias| alias.trim().to_string())
        .filter(|alias| !alias.is_empty());
    Ok(())
}

pub fn delete_identity(
    wallet: &mut Wallet,
    index: usize,
) -> Result<String, Box<dyn std::error::Error>> {
    if wallet.identities.len() <= 1 {
        return Err("wallet must keep at least one identity".into());
    }
    if index >= wallet.identities.len() {
        return Err(format!(
            "index {index} out of range (wallet has {} identit{})",
            wallet.identities.len(),
            if wallet.identities.len() == 1 {
                "y"
            } else {
                "ies"
            },
        )
        .into());
    }

    let npub = identity_npub(&wallet.identities[index])?;
    wallet.identities.remove(index);

    if wallet.active == index {
        wallet.active = index.min(wallet.identities.len().saturating_sub(1));
    } else if index < wallet.active {
        wallet.active = wallet.active.saturating_sub(1);
    }

    Ok(npub)
}
