//! Wallet types: in-memory representation of the decrypted wallet.

pub mod crypto;
pub mod io;

pub use io::{load_wallet, save_wallet, wallet_path};

/// Type of a wallet identity entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IdentityType {
    /// Auto-generated by ec-connect on first launch.
    Local,
    /// Imported by the player from an existing nsec.
    Imported,
}

impl IdentityType {
    pub fn as_str(&self) -> &'static str {
        match self {
            IdentityType::Local => "local",
            IdentityType::Imported => "imported",
        }
    }

    pub fn parse(s: &str) -> Result<Self, String> {
        match s {
            "local" => Ok(IdentityType::Local),
            "imported" => Ok(IdentityType::Imported),
            other => Err(format!("unknown identity type: {other}")),
        }
    }
}

/// One identity entry in the wallet.
#[derive(Debug, Clone)]
pub struct Identity {
    /// Nostr secret key in nsec bech32 format.
    pub nsec: String,
    /// Whether this identity was generated locally or imported.
    pub identity_type: IdentityType,
    /// ISO-8601 creation timestamp (UTC, second precision).
    pub created: String,
}

/// The in-memory wallet: a list of identities with one active.
#[derive(Debug, Clone)]
pub struct Wallet {
    /// Index into `identities` of the currently active identity.
    /// Stored as a string in KDL; parsed as `usize`.
    pub active: usize,
    /// Ordered list of identity entries.
    pub identities: Vec<Identity>,
}

impl Wallet {
    /// Create an empty wallet (no identities, active = 0).
    pub fn empty() -> Self {
        Wallet {
            active: 0,
            identities: Vec::new(),
        }
    }

    /// Return the active identity, if one exists.
    pub fn active_identity(&self) -> Option<&Identity> {
        self.identities.get(self.active)
    }
}
