#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StartupAction {
    Advance,
    ScrollReview(isize),
    SkipIntro,
    AcceptDefault,
    RejectChoice,
    EnableNonstop,
    OpenFirstTimeMenu,
    OpenFirstTimeHelp,
    OpenFirstTimeEmpires,
    OpenFirstTimeIntro,
    OpenThemePicker,
    MoveThemePicker(isize),
    AppendThemePickerChar(char),
    BackspaceThemePickerInput,
    ApplyThemePickerSelection,
    ExitThemePicker,
    OpenFirstTimeJoinName,
    AppendFirstTimeInputChar(char),
    BackspaceFirstTimeInput,
    SubmitFirstTimeInput,
    AcceptFirstTimePrompt,
    RejectFirstTimePrompt,
    OpenReports,
}
