use crate::domains::planet::screens::planet_commission::PlanetCommissionDraftRow;
use crate::domains::planet::screens::planet_transport::PlanetTransportMode;
use crate::screen::{
    PlanetDatabaseFilter, PlanetDatabasePromptMode, PlanetDatabaseSort, PlanetListFilter,
    PlanetListFilterPromptMode, PlanetListSort, SortDirection,
};
use crossterm::event::KeyCode;
use nc_data::{CampaignStore, PlanetIntelSnapshot, ProductionItemKind};
use nc_ui::table_filter::{TableFilterClause, TableFilterColumn};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlanetMenuTransportPromptMode {
    Fleet(PlanetTransportMode),
    Quantity(PlanetTransportMode),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlanetCommandContext {
    Menu,
    List,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlanetScorchPromptMode {
    Planet,
    Confirm1,
    Confirm2,
    Confirm3,
}

pub struct PlanetState {
    pub campaign_store: CampaignStore,
    pub intel_snapshots: BTreeMap<usize, PlanetIntelSnapshot>,
    pub command_context: PlanetCommandContext,
    pub brief_scroll_offset: usize,
    pub brief_cursor: usize,
    pub brief_input: String,
    pub list_sort: PlanetListSort,
    pub list_sort_direction: SortDirection,
    pub list_filter: PlanetListFilter,
    pub list_filter_clause: Option<TableFilterClause>,
    pub list_filter_pending_column: Option<TableFilterColumn>,
    pub list_filter_prompt_mode: PlanetListFilterPromptMode,
    pub list_prompt_input: String,
    pub list_prompt_default_value: String,
    pub list_pending_range_anchor: Option<[u8; 2]>,
    pub database_scroll_offset: usize,
    pub database_cursor: usize,
    pub database_input: String,
    pub database_prompt_default_value: String,
    pub database_pending_range_anchor: Option<[u8; 2]>,
    pub database_status: Option<String>,
    pub database_prompt_mode: PlanetDatabasePromptMode,
    pub database_filter: PlanetDatabaseFilter,
    pub database_filter_clause: Option<TableFilterClause>,
    pub database_pending_column: Option<TableFilterColumn>,
    pub database_sort: PlanetDatabaseSort,
    pub database_sort_direction: SortDirection,
    pub commission_index: usize,
    pub commission_picker_scroll_offset: usize,
    pub commission_cursor: usize,
    pub commission_scroll_offset: usize,
    pub commission_selected_slots: BTreeSet<usize>,
    pub commission_status: Option<String>,
    pub commission_draft_slots: Vec<usize>,
    pub commission_draft_rows: Vec<PlanetCommissionDraftRow>,
    pub commission_draft_cursor: usize,
    pub commission_draft_input: String,
    pub commission_draft_status: Option<String>,
    pub commission_draft_notice: Option<String>,
    pub commission_result_title: Option<String>,
    pub commission_result_return_to_picker: bool,
    pub commission_result_dismiss_key: Option<KeyCode>,
    pub commission_result_notice: Option<String>,
    pub auto_commission_prompt_active: bool,
    pub auto_commission_report_rows: Vec<String>,
    pub auto_commission_report_revealed_rows: usize,
    pub scorch_prompt_mode: Option<PlanetScorchPromptMode>,
    pub scorch_prompt_input: String,
    pub scorch_prompt_default_value: String,
    pub scorch_prompt_default_coords: Option<[u8; 2]>,
    pub scorch_prompt_status: Option<String>,
    pub scorch_selected_planet_record: Option<usize>,
    pub transport_mode: Option<PlanetTransportMode>,
    pub transport_planet_cursor: usize,
    pub transport_planet_scroll_offset: usize,
    pub transport_selected_planet_record: Option<usize>,
    pub transport_selected_fleet_record: Option<usize>,
    pub transport_fleet_first: bool,
    pub transport_prompt_mode: Option<PlanetMenuTransportPromptMode>,
    pub transport_prompt_input: String,
    pub transport_prompt_default_value: String,
    pub transport_planet_input: String,
    pub transport_fleet_cursor: usize,
    pub transport_fleet_scroll_offset: usize,
    pub transport_qty_input: String,
    pub transport_status: Option<String>,
    pub build_index: usize,
    pub build_return_to_list: bool,
    pub build_status: Option<String>,
    pub build_unit_input: String,
    pub build_unit_status: Option<String>,
    pub build_unit_notice: Option<String>,
    pub build_quantity_input: String,
    pub build_quantity_status: Option<String>,
    pub build_selected_kind: Option<ProductionItemKind>,
    pub build_list_scroll_offset: usize,
    pub build_list_cursor: usize,
    pub build_list_confirming: bool,
    pub build_list_delete_qty_prompt_active: bool,
    pub build_list_delete_qty_input: String,
    pub build_list_delete_qty_status: Option<String>,
    pub build_list_delete_qty_pending: Option<u32>,
    pub build_change_cursor: usize,
    pub build_change_scroll_offset: usize,
    pub build_abort_prompt_active: bool,
    pub tax_prompt_active: bool,
    pub tax_input: String,
    pub tax_error: Option<String>,
    pub tax_notice: Option<String>,
    pub info_prompt_active: bool,
    pub info_input: String,
    pub info_error: Option<String>,
    pub info_selected: Option<usize>,
    pub list_prompt_status: Option<String>,
}

impl PlanetState {
    pub fn new(
        campaign_store: CampaignStore,
        intel_snapshots: BTreeMap<usize, PlanetIntelSnapshot>,
    ) -> Self {
        Self {
            campaign_store,
            intel_snapshots,
            command_context: PlanetCommandContext::Menu,
            brief_scroll_offset: 0,
            brief_cursor: 0,
            brief_input: String::new(),
            list_sort: PlanetListSort::CurrentProduction,
            list_sort_direction: SortDirection::Desc,
            list_filter: PlanetListFilter::All,
            list_filter_clause: None,
            list_filter_pending_column: None,
            list_filter_prompt_mode: PlanetListFilterPromptMode::FilterMenu,
            list_prompt_input: String::new(),
            list_prompt_default_value: String::new(),
            list_pending_range_anchor: None,
            database_scroll_offset: 0,
            database_cursor: 0,
            database_input: String::new(),
            database_prompt_default_value: String::new(),
            database_pending_range_anchor: None,
            database_status: None,
            database_prompt_mode: PlanetDatabasePromptMode::FilterMenu,
            database_filter: PlanetDatabaseFilter::All,
            database_filter_clause: None,
            database_pending_column: None,
            database_sort: PlanetDatabaseSort::Location,
            database_sort_direction: SortDirection::Asc,
            commission_index: 0,
            commission_picker_scroll_offset: 0,
            commission_cursor: 0,
            commission_scroll_offset: 0,
            commission_selected_slots: BTreeSet::new(),
            commission_status: None,
            commission_draft_slots: Vec::new(),
            commission_draft_rows: Vec::new(),
            commission_draft_cursor: 0,
            commission_draft_input: String::new(),
            commission_draft_status: None,
            commission_draft_notice: None,
            commission_result_title: None,
            commission_result_return_to_picker: false,
            commission_result_dismiss_key: None,
            commission_result_notice: None,
            auto_commission_prompt_active: false,
            auto_commission_report_rows: Vec::new(),
            auto_commission_report_revealed_rows: 0,
            scorch_prompt_mode: None,
            scorch_prompt_input: String::new(),
            scorch_prompt_default_value: String::new(),
            scorch_prompt_default_coords: None,
            scorch_prompt_status: None,
            scorch_selected_planet_record: None,
            transport_mode: None,
            transport_planet_cursor: 0,
            transport_planet_scroll_offset: 0,
            transport_selected_planet_record: None,
            transport_selected_fleet_record: None,
            transport_fleet_first: false,
            transport_prompt_mode: None,
            transport_prompt_input: String::new(),
            transport_prompt_default_value: String::new(),
            transport_planet_input: String::new(),
            transport_fleet_cursor: 0,
            transport_fleet_scroll_offset: 0,
            transport_qty_input: String::new(),
            transport_status: None,
            build_index: 0,
            build_return_to_list: false,
            build_status: None,
            build_unit_input: String::new(),
            build_unit_status: None,
            build_unit_notice: None,
            build_quantity_input: String::new(),
            build_quantity_status: None,
            build_selected_kind: None,
            build_list_scroll_offset: 0,
            build_list_cursor: 0,
            build_list_confirming: false,
            build_list_delete_qty_prompt_active: false,
            build_list_delete_qty_input: String::new(),
            build_list_delete_qty_status: None,
            build_list_delete_qty_pending: None,
            build_change_cursor: 0,
            build_change_scroll_offset: 0,
            build_abort_prompt_active: false,
            tax_prompt_active: false,
            tax_input: String::new(),
            tax_error: None,
            tax_notice: None,
            info_prompt_active: false,
            info_input: String::new(),
            info_error: None,
            info_selected: None,
            list_prompt_status: None,
        }
    }
}
