pub fn print_usage() {
    println!("Usage:");
    println!("  ec-cli inspect [dir]");
    println!("  ec-cli core-report [dir]");
    println!("  ec-cli core-diff-current-known-baseline [dir]");
    println!("  ec-cli core-diff-current-known-baseline-offsets [dir]");
    println!("  ec-cli core-diff-canonical-current-known-baseline [dir]");
    println!("  ec-cli core-diff-canonical-current-known-baseline-offsets [dir]");
    println!("  ec-cli core-report-canonical-transition-clusters [dir]");
    println!("  ec-cli core-report-canonical-transition-details [dir]");
    println!("  ec-cli core-validate [dir]");
    println!("  ec-cli core-validate-current-known-baseline [dir]");
    println!("  ec-cli core-sync-counts [dir]");
    println!("  ec-cli core-sync-baseline [dir]");
    println!("  ec-cli core-sync-current-known-baseline [dir]");
    println!("  ec-cli core-sync-canonical-current-known-baseline [dir]");
    println!("  ec-cli core-sync-initialized-fleets [dir]");
    println!("  ec-cli core-sync-initialized-planets [dir]");
    println!("  ec-cli core-init-current-known-baseline [source_dir] <target_dir>");
    println!("  ec-cli core-init-canonical-current-known-baseline [source_dir] <target_dir>");
    println!("  ec-cli headers [dir]");
    println!("  ec-cli maintenance-days [dir]");
    println!("  ec-cli maintenance-days <dir> set <sun|mon|tue|wed|thu|fri|sat>...");
    println!("  ec-cli snoop [dir]");
    println!("  ec-cli snoop <dir> <on|off>");
    println!("  ec-cli purge-after [dir]");
    println!("  ec-cli purge-after <dir> <turns>");
    println!("  ec-cli fleet-order <dir> <fleet_record> <speed> <order_code> <target_x> <target_y> [aux0] [aux1]");
    println!("  ec-cli fleet-order-report [dir] [fleet_record]");
    println!("  ec-cli fleet-order-init <target_dir> <fleet_record> <speed> <order_code> <target_x> <target_y> [aux0] [aux1]");
    println!("  ec-cli fleet-order-batch-init <target_root> <fleet_record:speed:order:target_x:target_y[:aux0[:aux1]]>...");
    println!("  ec-cli planet-build <dir> <planet_record> <build_slot_raw> <build_kind_raw>");
    println!("  ec-cli planet-build-report [dir] [planet_record]");
    println!("  ec-cli planet-build-init <target_dir> <planet_record> <build_slot_raw> <build_kind_raw>");
    println!("  ec-cli planet-build-batch-init <target_root> <planet_record:build_slot_raw:build_kind_raw>...");
    println!("  ec-cli guard-starbase-onebase <dir> <target_x> <target_y>");
    println!("  ec-cli guard-starbase-report <dir>");
    println!("  ec-cli guard-starbase-init [source_dir] <target_dir> <target_x> <target_y>");
    println!("  ec-cli guard-starbase-batch-init [source_dir] <target_root> <x:y> <x:y>...");
    println!("  ec-cli ipbm-report <dir>");
    println!("  ec-cli ipbm-zero <dir> <count>");
    println!("  ec-cli ipbm-record-set <dir> <record_index> <primary> <owner> <gate> <follow_on>");
    println!("  ec-cli ipbm-validate <dir>");
    println!("  ec-cli ipbm-init [source_dir] <target_dir> <count>");
    println!("  ec-cli ipbm-batch-init [source_dir] <target_root> <count> <count>...");
    println!("  ec-cli compliance-report <dir>");
    println!("  ec-cli compliance-batch-report <root>");
    println!("  ec-cli scenario <dir> <fleet-order|planet-build|guard-starbase>");
    println!("  ec-cli scenario <dir> show <fleet-order|planet-build|guard-starbase>");
    println!("  ec-cli scenario <dir> compose <fleet-order|planet-build|guard-starbase>...");
    println!("  ec-cli scenario <dir> list");
    println!("  ec-cli scenario-init-all [source_dir] <target_root>");
    println!("  ec-cli scenario-init [source_dir] <target_dir> <fleet-order|planet-build|guard-starbase>");
    println!("  ec-cli scenario-init-compose [source_dir] <target_dir> <fleet-order|planet-build|guard-starbase>...");
    println!("  ec-cli validate <dir> <all|fleet-order|planet-build|guard-starbase>");
    println!("  ec-cli validate-preserved <dir> <all|fleet-order|planet-build|guard-starbase>");
    println!("  ec-cli compare-preserved <dir> <all|fleet-order|planet-build|guard-starbase>");
    println!("  ec-cli match [dir]");
    println!("  ec-cli compare <left_dir> <right_dir>");
    println!("  ec-cli init [source_dir] <target_dir>");
}
