use crate::domains::planet::screens::planet_transport::PlanetTransportMode;
use ec_data::{CampaignStore, PlanetIntelSnapshot, ProductionItemKind};
use std::collections::{BTreeMap, BTreeSet};

pub struct PlanetState {
    pub campaign_store: CampaignStore,
    pub intel_snapshots: BTreeMap<usize, PlanetIntelSnapshot>,
    pub brief_scroll_offset: usize,
    pub brief_cursor: usize,
    pub detail_index: usize,
    pub database_scroll_offset: usize,
    pub database_cursor: usize,
    pub database_detail_index: usize,
    pub database_input: String,
    pub database_status: Option<String>,
    pub commission_index: usize,
    pub commission_cursor: usize,
    pub commission_scroll_offset: usize,
    pub commission_selected_slots: BTreeSet<usize>,
    pub commission_status: Option<String>,
    pub auto_commission_status: Option<String>,
    pub transport_mode: Option<PlanetTransportMode>,
    pub transport_planet_cursor: usize,
    pub transport_planet_scroll_offset: usize,
    pub transport_selected_planet_record: Option<usize>,
    pub transport_planet_input: String,
    pub transport_fleet_cursor: usize,
    pub transport_fleet_scroll_offset: usize,
    pub transport_qty_input: String,
    pub transport_status: Option<String>,
    pub build_index: usize,
    pub build_status: Option<String>,
    pub build_unit_input: String,
    pub build_unit_status: Option<String>,
    pub build_quantity_input: String,
    pub build_quantity_status: Option<String>,
    pub build_selected_kind: Option<ProductionItemKind>,
    pub build_list_scroll_offset: usize,
    pub build_list_cursor: usize,
    pub build_list_confirming: bool,
    pub build_change_cursor: usize,
    pub build_change_scroll_offset: usize,
    pub tax_input: String,
    pub tax_status: Option<String>,
    pub info_input: String,
    pub info_error: Option<String>,
    pub info_selected: Option<usize>,
    pub list_sort_status: Option<String>,
}

impl PlanetState {
    pub fn new(
        campaign_store: CampaignStore,
        intel_snapshots: BTreeMap<usize, PlanetIntelSnapshot>,
    ) -> Self {
        Self {
            campaign_store,
            intel_snapshots,
            brief_scroll_offset: 0,
            brief_cursor: 0,
            detail_index: 0,
            database_scroll_offset: 0,
            database_cursor: 0,
            database_detail_index: 0,
            database_input: String::new(),
            database_status: None,
            commission_index: 0,
            commission_cursor: 0,
            commission_scroll_offset: 0,
            commission_selected_slots: BTreeSet::new(),
            commission_status: None,
            auto_commission_status: None,
            transport_mode: None,
            transport_planet_cursor: 0,
            transport_planet_scroll_offset: 0,
            transport_selected_planet_record: None,
            transport_planet_input: String::new(),
            transport_fleet_cursor: 0,
            transport_fleet_scroll_offset: 0,
            transport_qty_input: String::new(),
            transport_status: None,
            build_index: 0,
            build_status: None,
            build_unit_input: String::new(),
            build_unit_status: None,
            build_quantity_input: String::new(),
            build_quantity_status: None,
            build_selected_kind: None,
            build_list_scroll_offset: 0,
            build_list_cursor: 0,
            build_list_confirming: false,
            build_change_cursor: 0,
            build_change_scroll_offset: 0,
            tax_input: String::new(),
            tax_status: None,
            info_input: String::new(),
            info_error: None,
            info_selected: None,
            list_sort_status: None,
        }
    }
}
