use std::collections::BTreeSet;
use ec_data::FleetDetachSelection;
use crate::screen::FleetListMode;
use crate::domains::fleet::screens::fleet::{
    FleetSingleOrderMode, FleetGroupOrderMode, FleetMergeMode, FleetTransferMode,
    FleetDetachMode, FleetEtaMode,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FleetMissionPickerCaller {
    GroupOrder,
    SingleOrder,
}

pub struct FleetState {
    pub scroll_offset: usize,
    pub cursor: usize,
    pub list_mode: FleetListMode,
    pub review_index: usize,
    pub review_select_input: String,
    pub review_status: Option<String>,
    pub roe_scroll_offset: usize,
    pub roe_cursor: usize,
    pub roe_editing: bool,
    pub roe_select_input: String,
    pub roe_input: String,
    pub roe_status: Option<String>,
    pub order_scroll_offset: usize,
    pub order_cursor: usize,
    pub order_mode: FleetSingleOrderMode,
    pub order_fleet_record_index_1_based: Option<usize>,
    pub order_input: String,
    pub order_status: Option<String>,
    pub order_mission_code: Option<u8>,
    pub group_scroll_offset: usize,
    pub group_cursor: usize,
    pub group_mode: FleetGroupOrderMode,
    pub group_selected_fleets: BTreeSet<usize>,
    pub group_mission_code: Option<u8>,
    pub group_input: String,
    pub group_status: Option<String>,
    pub mission_picker_cursor: usize,
    pub mission_picker_input: String,
    pub mission_picker_status: Option<String>,
    pub mission_picker_caller: Option<FleetMissionPickerCaller>,
    pub merge_scroll_offset: usize,
    pub merge_cursor: usize,
    pub merge_mode: FleetMergeMode,
    pub merge_source_record_index_1_based: Option<usize>,
    pub merge_source_input: String,
    pub merge_host_input: String,
    pub merge_status: Option<String>,
    pub transfer_scroll_offset: usize,
    pub transfer_cursor: usize,
    pub transfer_mode: FleetTransferMode,
    pub transfer_selected_fleets: BTreeSet<usize>,
    pub transfer_donor_record_index_1_based: Option<usize>,
    pub transfer_host_record_index_1_based: Option<usize>,
    pub transfer_select_input: String,
    pub transfer_input: String,
    pub transfer_status: Option<String>,
    pub transfer_selection: FleetDetachSelection,
    pub detach_scroll_offset: usize,
    pub detach_cursor: usize,
    pub detach_mode: FleetDetachMode,
    pub detach_select_input: String,
    pub detach_input: String,
    pub detach_status: Option<String>,
    pub detach_selection: FleetDetachSelection,
    pub detach_donor_speed: Option<u8>,
    pub eta_scroll_offset: usize,
    pub eta_cursor: usize,
    pub eta_mode: FleetEtaMode,
    pub eta_select_input: String,
    pub eta_destination_input: String,
    pub eta_include_system_input: String,
    pub eta_status: Option<String>,
}

impl Default for FleetState {
    fn default() -> Self {
        Self {
            scroll_offset: 0,
            cursor: 0,
            list_mode: FleetListMode::Brief,
            review_index: 0,
            review_select_input: String::new(),
            review_status: None,
            roe_scroll_offset: 0,
            roe_cursor: 0,
            roe_editing: false,
            roe_select_input: String::new(),
            roe_input: String::new(),
            roe_status: None,
            order_scroll_offset: 0,
            order_cursor: 0,
            order_mode: FleetSingleOrderMode::SelectingFleet,
            order_fleet_record_index_1_based: None,
            order_input: String::new(),
            order_status: None,
            order_mission_code: None,
            group_scroll_offset: 0,
            group_cursor: 0,
            group_mode: FleetGroupOrderMode::SelectingFleets,
            group_selected_fleets: BTreeSet::new(),
            group_mission_code: None,
            group_input: String::new(),
            group_status: None,
            mission_picker_cursor: 0,
            mission_picker_input: String::new(),
            mission_picker_status: None,
            mission_picker_caller: None,
            merge_scroll_offset: 0,
            merge_cursor: 0,
            merge_mode: FleetMergeMode::SelectingSource,
            merge_source_record_index_1_based: None,
            merge_source_input: String::new(),
            merge_host_input: String::new(),
            merge_status: None,
            transfer_scroll_offset: 0,
            transfer_cursor: 0,
            transfer_mode: FleetTransferMode::SelectingFleets,
            transfer_selected_fleets: BTreeSet::new(),
            transfer_donor_record_index_1_based: None,
            transfer_host_record_index_1_based: None,
            transfer_select_input: String::new(),
            transfer_input: String::new(),
            transfer_status: None,
            transfer_selection: FleetDetachSelection::default(),
            detach_scroll_offset: 0,
            detach_cursor: 0,
            detach_mode: FleetDetachMode::SelectingFleet,
            detach_select_input: String::new(),
            detach_input: String::new(),
            detach_status: None,
            detach_selection: FleetDetachSelection::default(),
            detach_donor_speed: None,
            eta_scroll_offset: 0,
            eta_cursor: 0,
            eta_mode: FleetEtaMode::SelectingFleet,
            eta_select_input: String::new(),
            eta_destination_input: String::new(),
            eta_include_system_input: String::new(),
            eta_status: None,
        }
    }
}
