use crate::domains::fleet::screens::fleet::{
    FleetDetachMode, FleetEtaMode, FleetGroupOrderMode, FleetListFilter, FleetListSort,
    FleetSingleOrderMode, FleetTransferMode,
};
use crate::screen::layout::PromptFeedback;
use crate::screen::{PlanetTransportMode, SortDirection};
use nc_data::FleetDetachSelection;
use std::collections::BTreeSet;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FleetChangeField {
    Roe,
    Id,
    Speed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FleetMenuPromptMode {
    Review,
    Order,
    ChangeFleet,
    ChangeField,
    ChangeValue,
    EtaFleet,
    DetachFleet,
    MergeSource,
    MergeHost,
    TransferDonor,
    TransferHost,
    TransportFleet(PlanetTransportMode),
    TransportQuantity(PlanetTransportMode),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FleetMissionPickerCaller {
    GroupOrder,
    SingleOrderReturnToOrder,
    SingleOrderReturnToMenu,
    SingleOrderReturnToList,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FleetCommandContext {
    Menu,
    List,
}

pub struct FleetState {
    pub scroll_offset: usize,
    pub cursor: usize,
    pub list_input: String,
    pub list_status: Option<String>,
    pub list_dismiss_message: Option<String>,
    pub list_sort: FleetListSort,
    pub list_sort_direction: SortDirection,
    pub list_filter: FleetListFilter,
    pub menu_prompt_mode: Option<FleetMenuPromptMode>,
    pub menu_prompt_input: String,
    pub menu_prompt_status: Option<PromptFeedback>,
    pub menu_prompt_default_value: String,
    pub menu_prompt_context_fleet_record_index_1_based: Option<usize>,
    pub menu_prompt_change_field: Option<FleetChangeField>,
    pub review_index: usize,
    pub review_return_to_list: bool,
    pub order_fleet_record_index_1_based: Option<usize>,
    pub order_mode: FleetSingleOrderMode,
    pub order_input: String,
    pub order_target_x_input: String,
    pub order_target_y_input: String,
    pub order_confirm_input: String,
    pub order_status: Option<String>,
    pub order_mission_code: Option<u8>,
    pub order_return_to_menu: bool,
    pub recently_commissioned_fleet_records_mru: Vec<usize>,
    pub group_scroll_offset: usize,
    pub group_cursor: usize,
    pub group_mode: FleetGroupOrderMode,
    pub group_selected_fleets: BTreeSet<usize>,
    pub group_mission_code: Option<u8>,
    pub group_input: String,
    pub group_target_x_input: String,
    pub group_target_y_input: String,
    pub group_confirm_input: String,
    pub group_status: Option<String>,
    pub mission_picker_cursor: usize,
    pub mission_picker_input: String,
    pub mission_picker_status: Option<String>,
    pub mission_picker_caller: Option<FleetMissionPickerCaller>,
    pub merge_source_record_index_1_based: Option<usize>,
    pub transfer_mode: FleetTransferMode,
    pub transfer_donor_record_index_1_based: Option<usize>,
    pub transfer_host_record_index_1_based: Option<usize>,
    pub transfer_input: String,
    pub transfer_status: Option<String>,
    pub transfer_selection: FleetDetachSelection,
    pub detach_donor_record_index_1_based: Option<usize>,
    pub detach_mode: FleetDetachMode,
    pub detach_input: String,
    pub detach_status: Option<String>,
    pub detach_last_commissioned: Option<String>,
    pub detach_selection: FleetDetachSelection,
    pub detach_donor_speed: Option<u8>,
    pub eta_fleet_record_index_1_based: Option<usize>,
    pub eta_mode: FleetEtaMode,
    pub eta_destination_input: String,
    pub eta_include_system_input: String,
    pub eta_status: Option<String>,
    pub command_context: FleetCommandContext,
    pub dismiss_message: Option<String>,
}

impl Default for FleetState {
    fn default() -> Self {
        Self {
            scroll_offset: 0,
            cursor: 0,
            list_input: String::new(),
            list_status: None,
            list_dismiss_message: None,
            list_sort: FleetListSort::Id,
            list_sort_direction: SortDirection::Desc,
            list_filter: FleetListFilter::All,
            menu_prompt_mode: None,
            menu_prompt_input: String::new(),
            menu_prompt_status: None,
            menu_prompt_default_value: String::new(),
            menu_prompt_context_fleet_record_index_1_based: None,
            menu_prompt_change_field: None,
            review_index: 0,
            review_return_to_list: false,
            order_fleet_record_index_1_based: None,
            order_mode: FleetSingleOrderMode::EnteringTarget,
            order_input: String::new(),
            order_target_x_input: String::new(),
            order_target_y_input: String::new(),
            order_confirm_input: String::new(),
            order_status: None,
            order_mission_code: None,
            order_return_to_menu: false,
            recently_commissioned_fleet_records_mru: Vec::new(),
            group_scroll_offset: 0,
            group_cursor: 0,
            group_mode: FleetGroupOrderMode::SelectingFleets,
            group_selected_fleets: BTreeSet::new(),
            group_mission_code: None,
            group_input: String::new(),
            group_target_x_input: String::new(),
            group_target_y_input: String::new(),
            group_confirm_input: String::new(),
            group_status: None,
            mission_picker_cursor: 0,
            mission_picker_input: String::new(),
            mission_picker_status: None,
            mission_picker_caller: None,
            merge_source_record_index_1_based: None,
            transfer_mode: FleetTransferMode::ChoosingClass,
            transfer_donor_record_index_1_based: None,
            transfer_host_record_index_1_based: None,
            transfer_input: String::new(),
            transfer_status: None,
            transfer_selection: FleetDetachSelection::default(),
            detach_donor_record_index_1_based: None,
            detach_mode: FleetDetachMode::ChoosingClass,
            detach_input: String::new(),
            detach_status: None,
            detach_last_commissioned: None,
            detach_selection: FleetDetachSelection::default(),
            detach_donor_speed: None,
            eta_fleet_record_index_1_based: None,
            eta_mode: FleetEtaMode::EnteringDestination,
            eta_destination_input: String::new(),
            eta_include_system_input: String::new(),
            eta_status: None,
            command_context: FleetCommandContext::Menu,
            dismiss_message: None,
        }
    }
}
