#!/bin/bash
# Wrapper script to launch Esterian Conquest (DOS) from Enigma BBS
# Usage: run_ec_dos.sh <dropfile_path> <node_number>

DROPFILE=$1
NODE=$2
GAME_DIR="/home/mag/dev/esterian_conquest/original/v1.5"

# Copy the dropfile generated by Enigma to the game directory
# EC expects DOOR.SYS by default, so we ensure it's named that way
cp "$DROPFILE" "$GAME_DIR/DOOR.SYS"

# Launch DOSBox-X
# -c commands run sequentially inside DOSBox-X
# We mount the game dir, switch to C:, run ECBBS, and exit when done
dosbox-x -conf /dev/null \
  -fastlaunch \
  -c "mount c $GAME_DIR" \
  -c "c:" \
  -c "ECBBS.EXE" \
  -c "exit"
