#!/bin/bash
# Wrapper script to launch Esterian Conquest (DOS) from Enigma BBS
# Usage: run_ec_dos.sh <dropfile_path> <node_number> <server_port>

DROPFILE=$1
NODE=$2
PORT=$3
GAME_DIR="/home/mag/dev/esterian_conquest/original/v1.5"

# Log what's happening to help debug
echo "Launch triggered with DROPFILE: $DROPFILE, NODE: $NODE, PORT: $PORT" >> /tmp/ec_door.log

# Copy the dropfile generated by Enigma to the game directory
cp "$DROPFILE" "$GAME_DIR/DOOR.SYS"
chmod 666 "$GAME_DIR/DOOR.SYS"

export SDL_VIDEODRIVER=dummy

# Enigma will connect DOSBox's COM1 serial port to the Telnet socket
# via virtual null modem connection over TCP/IP
dosbox-x -conf /dev/null \
  -fastlaunch \
  -nogui \
  -c "serial1=nullmodem server:127.0.0.1 port:$PORT" \
  -c "mount c $GAME_DIR" \
  -c "c:" \
  -c "ECBBS.EXE /D:C:\\ /N:$NODE" \
  -c "exit" 
