from pathlib import Path


def _write_crlf_lines(path: str | Path, lines: list[str]) -> None:
    Path(path).write_bytes(("\r\n".join(lines) + "\r\n").encode("ascii"))


def write_chain_txt(
    path: str | Path,
    *,
    player_number: int = 1,
    alias: str = "Sysop",
    real_name: str = "Sysop",
    callsign: str = "",
    age: int = 42,
    sex: str = "M",
    gold: str = "0.00",
    last_logon_date: str = "03/13/26",
    columns: int = 80,
    width: int = 25,
    security_level: int = 25,
    co_sysop: int = 0,
    sysop: int = 1,
    ansi: int = 1,
    remote: int = 0,
    seconds_left: str = "3600",
    gfiles_dir: str = r"C:\GFILES\\",
    data_dir: str = r"C:\DATA\\",
    log_name: str = "ECGAME.LOG",
    user_baud: int = 0,
    com_port: int = 0,
    system_name: str = "Esterian Conquest",
    system_sysop: str = "Sysop",
    login_time: str = "0",
    seconds_on: str = "0",
    uploaded_k: str = "0",
    uploads: int = 0,
    downloaded_k: str = "0",
    downloads: int = 0,
    parity: str = "8N1",
    com_baud: int = 0,
    wwivnet_node: str = "0",
) -> None:
    # WWIV-style CHAIN.TXT: 32 CRLF-terminated lines.
    # ECGAME proved sensitive to both field count and field order.
    lines = [
        str(player_number),
        alias,
        real_name,
        callsign,
        str(age),
        sex,
        gold,
        last_logon_date,
        str(columns),
        str(width),
        str(security_level),
        str(co_sysop),
        str(sysop),
        str(ansi),
        str(remote),
        str(seconds_left),
        gfiles_dir,
        data_dir,
        log_name,
        str(user_baud),
        str(com_port),
        system_name,
        system_sysop,
        login_time,
        seconds_on,
        uploaded_k,
        str(uploads),
        downloaded_k,
        str(downloads),
        parity,
        str(com_baud),
        wwivnet_node,
    ]
    _write_crlf_lines(path, lines)


def write_door_sys(
    path: str | Path,
    *,
    com_port: str = "COM1:",
    baud: int = 19200,
    data_bits: int = 8,
    parity: str = "N",
    stop_bits: int = 1,
    user_first_name: str = "Sysop",
    user_last_name: str = "HANNIBAL",
    location: str = "Orlando, FL",
    phone: str = "123-456-7890",
) -> None:
    lines = [
        com_port,
        str(baud),
        str(data_bits),
        parity,
        str(stop_bits),
        "1",
        "Y",
        "Y",
        "Y",
        "Y",
        user_first_name,
        user_last_name,
        location,
        phone,
        "1",
        "0",
        "100",
        "9000",
        "1",
        "99",
    ] + ["90"] * 36
    _write_crlf_lines(path, lines)
